server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/task_management_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rahul@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configurations (512-bit secure hex key)
app.jwt-secret=8f1c8413a28bcf62e08bc05161c5df60e18105c317f22bb425c27bf62b66d4ee29388df634f19bc3230b42f61e8880bf59a1f22bb48c5df69a5a54ef6e8b80e8
app.jwt-expiration-milliseconds=86400000

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
